name: CI-CD Pipeline for Minfy Deployment CLI Tool

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      env:
        description: "minfy environment (dev / staging / prod)"
        required: false
        default: "prod"

env:
  AWS_REGION: ap-south-1
  MINFY_ENV: ${{ github.event.inputs.env || 'prod' }}

jobs:
  Minfy-Deployment-CLI-Tool:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install minfy CLI (editable)
      run: |
        cd minfy-cli
        python -m pip install --upgrade pip
        pip install -e .

    - name: Set up Terraform CLI
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION }}

    - name: Minfy Init
      run: |
        cd minfy-cli
        minfy init --repo https://github.com/maciekt07/TodoApp || true

    - name: Minfy Detect
      run: |
        cd minfy-cli
        minfy detect

    - name: Minfy Config Env
      run: |
        cd minfy-cli
        minfy config env ${{ env.MINFY_ENV }}
        minfy config list
        minfy config set SAMPLE_KEY=SAMPLE_VALUE

    - name: Minfy Deploy
      run: |
        cd minfy-cli
        minfy deploy

    - name: Minfy Status
      run: |
        cd minfy-cli
        minfy status

    - name: Minfy Rollback
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.env == 'destroy'
      run: |
        cd minfy-cli
        minfy rollback

    - name: Minfy Monitor Init
      run: |
        cd minfy-cli
        minfy monitor init

    - name: Minfy Monitor Enable
      run: |
        cd minfy-cli
        minfy monitor enable

    - name: Minfy Monitor Status
      run: |
        cd minfy-cli
        minfy monitor status

    - name: Minfy Monitor Dashboard
      run: |
        cd minfy-cli
        minfy monitor dashboard

    - name: Minfy Monitor Disable
      if: always()
      run: |
        cd minfy-cli
        minfy monitor disable

    - name: Minfy Monitor Cleanup
      if: always()
      run: |
        cd minfy-cli
        minfy monitor cleanup