name: CI / CD – minfy static-site pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      env:
        description: "minfy environment (dev / staging / prod)"
        required: false
        default: "prod"

env:
  AWS_REGION: ap-south-1
  MINFY_ENV: ${{ github.event.inputs.env || 'prod' }}

jobs:
  build-deploy-monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    # 1 · Checkout source
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    # 2 · Tool-chain setup
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install minfy CLI (editable)
      run: |
        cd minfy-cli
        python -m pip install --upgrade pip
        pip install -e .

    # Node.js setup removed (not needed; builds handled via Docker)

    - name: Set up Terraform CLI
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION }}


    # 4 · Initialize minfy workspace (git repo)
    - name: Minfy Init
      run: |
        cd minfy-cli
        minfy init --repo https://github.com/pandeyshivam-debug/recipe-finder-react || true

    # 5 · Detect framework and create build plan
    - name: Minfy Detect
      run: |
        cd minfy-cli
        minfy detect

    # 6 · Configure environment and variables
    - name: Minfy Config Env
      run: |
        cd minfy-cli
        minfy config env ${{ env.MINFY_ENV }}
        minfy config list
        minfy config set SAMPLE_KEY=SAMPLE_VALUE

    # 7 · Deploy to AWS S3 (with optional env file)
    - name: Minfy Deploy
      run: |
        cd minfy-cli
        minfy deploy

    # 8 · Check deployment status
    - name: Minfy Status
      run: |
        cd minfy-cli
        minfy status

    # 9 · Rollback (if needed)
    - name: Minfy Rollback
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.env == 'rollback'
      run: |
        cd minfy-cli
        minfy rollback

    # 10 · Monitoring stack setup
    - name: Minfy Monitor Init
      run: |
        cd minfy-cli
        minfy monitor init

    - name: Minfy Monitor Enable
      run: |
        cd minfy-cli
        minfy monitor enable

    - name: Minfy Monitor Status
      run: |
        cd minfy-cli
        minfy monitor status

    - name: Minfy Monitor Dashboard
      run: |
        cd minfy-cli
        minfy monitor dashboard

    - name: Minfy Monitor Disable
      if: always()
      run: |
        cd minfy-cli
        minfy monitor disable

    - name: Upload monitor SSH key (optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: monitor-ssh-key
        path: minfy-cli/.minfy_monitor/minfy_monitor.pem
        retention-days: 7